# Generated by Django 3.1.4 on 2020-12-02 10:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('sample_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=4096)),
                ('hash_md5', models.CharField(max_length=32, null=True)),
                ('hash_sha1', models.CharField(max_length=40, null=True)),
                ('hash_sha256', models.CharField(max_length=64, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_scanned', models.DateTimeField(null=True)),
                ('file_size', models.IntegerField()),
            ],
            options={
                'db_table': 'malsearch_sample',
            },
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('scan_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_time_scanned', models.DateTimeField()),
                ('file_type', models.CharField(max_length=1024, null=True)),
                ('platform', models.CharField(max_length=1024, null=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_results', to='malsearch.sample')),
            ],
            options={
                'db_table': 'malsearch_scanresult',
            },
        ),
    ]
