# Generated by Django 3.1.4 on 2020-12-02 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('malsearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sample',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='scanresult',
            options={'managed': True},
        ),
    ]
