# Generated by Django 3.1.4 on 2020-12-02 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('malsearch', '0002_auto_20201202_1438'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sample',
            table=None,
        ),
        migrations.AlterModelTable(
            name='scanresult',
            table=None,
        ),
    ]
