# Generated by Django 3.1.4 on 2020-12-07 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('malsearch', '0003_auto_20201202_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sample',
            options={},
        ),
        migrations.AlterModelOptions(
            name='scanresult',
            options={},
        ),
    ]
